disk_app_colprops = {
    'disk_region': HtmlTableColumn(
             title='Disk Region',
             table='b_disk_app',
             field='disk_region',
             img='hd16',
             display=False,
             _class="pre",
            ),
    'disk_id': HtmlTableColumn(
             title='Disk Id',
             table='b_disk_app',
             field='disk_id',
             img='hd16',
             display=True,
             _class="pre",
             _dataclass="bluer",
            ),
    'disk_name': HtmlTableColumn(
             title='Disk Name',
             table='b_disk_app',
             field='disk_name',
             img='hd16',
             display=True,
             _class="pre",
             _dataclass="bluer",
            ),
    'disk_svcname': HtmlTableColumn(
             title='Service',
             table='b_disk_app',
             field='disk_svcname',
             img='svc',
             display=True,
             _class = 'svcname',
            ),
    'disk_nodename': HtmlTableColumn(
             title='Nodename',
             table='b_disk_app',
             field='disk_nodename',
             img='hw16',
             display=True,
             _class="nodename",
            ),
    'disk_used': HtmlTableColumn(
             title='Disk Used',
             table='b_disk_app',
             field='disk_used',
             img='hd16',
             display=True,
             _class="numeric size_mb",
            ),
    'disk_local': HtmlTableColumn(
             title='Disk Local',
             table='b_disk_app',
             field='disk_local',
             img='hd16',
             display=True,
            ),
    'disk_size': HtmlTableColumn(
             title='Disk Size',
             table='b_disk_app',
             field='disk_size',
             img='hd16',
             display=True,
             _class="numeric size_mb",
             _dataclass="bluer",
            ),
    'disk_alloc': HtmlTableColumn(
             title='Disk Allocation',
             table='b_disk_app',
             field='disk_alloc',
             img='hd16',
             display=True,
             _class="numeric size_mb",
             _dataclass="bluer",
            ),
    'disk_vendor': HtmlTableColumn(
             title='Disk Vendor',
             table='b_disk_app',
             field='disk_vendor',
             img='hd16',
             display=True,
            ),
    'disk_model': HtmlTableColumn(
             title='Disk Model',
             table='b_disk_app',
             field='disk_model',
             img='hd16',
             display=True,
            ),
    'disk_dg': HtmlTableColumn(
             title='System disk group',
             table='b_disk_app',
             field='disk_dg',
             img='hd16',
             display=True,
            ),
    'disk_group': HtmlTableColumn(
             title='Array disk group',
             table='b_disk_app',
             field='disk_group',
             img='hd16',
             display=True,
             _class="disk_array_dg",
             _dataclass="bluer",
            ),
    'disk_level': HtmlTableColumn(
             title='Level',
             table='b_disk_app',
             field='disk_level',
             img='hd16',
             display=True,
             _dataclass="bluer",
            ),
    'disk_raid': HtmlTableColumn(
             title='Raid',
             table='b_disk_app',
             field='disk_raid',
             img='hd16',
             display=True,
             _dataclass="bluer",
            ),
    'svcdisk_updated': HtmlTableColumn(
             title='System Updated',
             table='b_disk_app',
             field='svcdisk_updated',
             img='time16',
             display=True,
             _class="datetime_daily",
            ),
    'disk_created': HtmlTableColumn(
             title='Storage Created',
             table='b_disk_app',
             field='disk_created',
             img='time16',
             display=True,
             _dataclass="bluer",
            ),
    'disk_updated': HtmlTableColumn(
             title='Storage Updated',
             table='b_disk_app',
             field='disk_updated',
             img='time16',
             display=True,
             _dataclass="datetime_daily bluer",
            ),
    'svcdisk_id': HtmlTableColumn(
             title='System Disk Id',
             table='b_disk_app',
             field='svcdisk_id',
             img='hd16',
             display=True,
             _class="disk_array",
             _dataclass="bluer",
            ),
    'disk_arrayid': HtmlTableColumn(
             title='Array Id',
             table='b_disk_app',
             field='disk_arrayid',
             img='hd16',
             display=True,
             _class="disk_array",
             _dataclass="bluer",
            ),
    'disk_devid': HtmlTableColumn(
             title='Array device Id',
             table='b_disk_app',
             field='disk_devid',
             img='hd16',
             display=True,
             _class="pre",
             _dataclass="bluer",
            ),
    'array_model': HtmlTableColumn(
             title='Array Model',
             table='stor_array',
             field='array_model',
             img='hd16',
             display=True,
             _dataclass="bluer",
            ),
    'app': HtmlTableColumn(
             title='App',
             table='b_disk_app',
             field='app',
             img='svc',
             display=True,
            ),
}


