v_services_cols = [
    'svc_status',
    'svc_availstatus',
    'svc_app',
    'svc_type',
    'svc_ha',
    'svc_cluster_type',
    'svc_flex_min_nodes',
    'svc_flex_max_nodes',
    'svc_flex_cpu_low_threshold',
    'svc_flex_cpu_high_threshold',
    'svc_drptype',
    'svc_containertype',
    'svc_autostart',
    'svc_nodes',
    'svc_drpnode',
    'svc_drpnodes',
    'svc_comment',
    'svc_created',
    'svc_updated',
]

svcmon_cols = [
    'mon_vmname',
    'mon_vmtype',
    'mon_guestos',
    'mon_vcpus',
    'mon_vmem',
    'mon_overallstatus',
    'mon_availstatus',
    'mon_updated',
    'mon_changed',
    'mon_frozen',
    'mon_containerstatus',
    'mon_ipstatus',
    'mon_fsstatus',
    'mon_diskstatus',
    'mon_sharestatus',
    'mon_syncstatus',
    'mon_appstatus',
    'mon_hbstatus'
]

v_services_colprops = {
    'svc_name': HtmlTableColumn(
             title = 'Service',
             field='svc_name',
             display = False,
             img = 'svc',
             table = 'v_services',
             _class='svcname',
            ),
    'svc_hostid': HtmlTableColumn(
             title = 'Host id',
             field='svc_hostid',
             display = False,
             img = 'svc',
             table = 'v_services',
            ),
    'svc_wave': HtmlTableColumn(
             title = 'Drp wave',
             field='svc_wave',
             display = False,
             img = 'svc',
             table = 'v_services',
            ),
    'svc_availstatus': HtmlTableColumn(
             title = 'Service availability status',
             field='svc_availstatus',
             display = True,
             img = 'svc',
             table = 'v_services',
             _class = 'status',
            ),
    'svc_status': HtmlTableColumn(
             title = 'Service overall status',
             field='svc_status',
             display = True,
             img = 'svc',
             table = 'v_services',
             _class = 'status',
            ),
    'svc_app': HtmlTableColumn(
             title = 'App',
             field='svc_app',
             display = False,
             img = 'svc',
             table = 'v_services',
            ),
    'svc_ha': HtmlTableColumn(
             title = 'HA',
             field='svc_ha',
             display = True,
             img = 'svc',
             table = 'v_services',
             _class = 'svc_ha',
            ),
    'svc_containertype': HtmlTableColumn(
             title = 'Service mode',
             field='svc_containertype',
             display = False,
             img = 'svc',
             table = 'v_services',
            ),
    'svc_type': HtmlTableColumn(
             title = 'Service type',
             field='svc_type',
             display = False,
             img = 'svc',
             table = 'v_services',
             _class = 'env',
            ),
    'svc_autostart': HtmlTableColumn(
             title = 'Primary node',
             field='svc_autostart',
             display = False,
             img = 'svc',
             table = 'v_services',
             _class = 'svc_autostart',
            ),
    'svc_nodes': HtmlTableColumn(
             title = 'Nodes',
             field='svc_nodes',
             display = False,
             img = 'svc',
             table = 'v_services',
            ),
    'svc_drpnode': HtmlTableColumn(
             title = 'DRP node',
             field='svc_drpnode',
             display = False,
             img = 'svc',
             table = 'v_services',
             _class = 'nodename_no_os',
            ),
    'svc_drpnodes': HtmlTableColumn(
             title = 'DRP nodes',
             field='svc_drpnodes',
             display = False,
             img = 'svc',
             table = 'v_services',
            ),
    'svc_drptype': HtmlTableColumn(
             title = 'DRP type',
             field='svc_drptype',
             display = False,
             img = 'svc',
             table = 'v_services',
            ),
    'svc_comment': HtmlTableColumn(
             title = 'Comment',
             field='svc_comment',
             display = False,
             img = 'svc',
             table = 'v_services',
            ),
    'svc_created': HtmlTableColumn(
             title = 'Service creation date',
             field='svc_created',
             display = False,
             img = 'time16',
             table = 'v_services',
            ),
    'svc_updated': HtmlTableColumn(
             title = 'Last service update',
             field='updated',
             display = False,
             img = 'time16',
             table = 'v_services',
             _class = 'datetime_daily',
            ),
    'svc_status_updated': HtmlTableColumn(
             title='Status updated',
             table='services',
             field='svc_status_updated',
             img='time16',
             display=True,
             _class='datetime_status',
            ),
    'responsibles': HtmlTableColumn(
             title = 'Responsibles',
             field='responsibles',
             display = False,
             img = 'guy16',
             table = 'v_services',
            ),
    'mailto': HtmlTableColumn(
             title = 'Responsibles emails',
             field='mailto',
             display = False,
             img = 'guy16',
             table = 'v_services',
            ),
    'svc_cluster_type': HtmlTableColumn(
             title = 'Cluster type',
             field='svc_cluster_type',
             display = True,
             img = 'svc',
             table = 'v_services',
            ),
    'svc_flex_min_nodes': HtmlTableColumn(
             title = 'Flex min nodes',
             field='svc_flex_min_nodes',
             display = False,
             img = 'svc',
             table = 'v_services',
            ),
    'svc_flex_max_nodes': HtmlTableColumn(
             title = 'Flex max nodes',
             field='svc_flex_max_nodes',
             display = False,
             img = 'svc',
             table = 'v_services',
            ),
    'svc_flex_cpu_low_threshold': HtmlTableColumn(
             title = 'Flex cpu low threshold',
             field='svc_flex_cpu_low_threshold',
             display = False,
             img = 'spark16',
             table = 'v_services',
            ),
    'svc_flex_cpu_high_threshold': HtmlTableColumn(
             title = 'Flex cpu high threshold',
             field='svc_flex_cpu_high_threshold',
             display = False,
             img = 'spark16',
             table = 'v_services',
            ),
    'svc_envfile': HtmlTableColumn(
             title = 'Env file',
             field='svc_envfile',
             display = False,
             img = 'svc',
             table = 'v_services',
            ),
    'svc_envdate': HtmlTableColumn(
             title = 'Env file date',
             field='svc_envdate',
             display = False,
             img = 'time16',
             table = 'v_svcmon',
            ),
}

v_svcmon_colprops = {
    'err': HtmlTableColumn(
             title = 'Action errors',
             field='err',
             display = False,
             img = 'action16',
             table = 'v_svcmon',
             _class = 'svc_action_err',
            ),
}

svcmon_colprops = {
    'mon_containerpath': HtmlTableColumn(
             title = 'Container path',
             field='mon_containerpath',
             display = False,
             img = 'svc',
             table = 'svcmon',
            ),
    'mon_svcname': HtmlTableColumn(
             title = 'Service',
             field='mon_svcname',
             display = False,
             img = 'svc',
             table = 'svcmon',
             _class = 'svcname',
            ),
    'mon_nodname': HtmlTableColumn(
             title = 'Node',
             field='mon_nodname',
             display = False,
             img = 'node16',
             table = 'svcmon',
             _class = 'nodename',
            ),
    'mon_svctype': HtmlTableColumn(
             title = 'Service type',
             field='mon_svctype',
             display = False,
             img = 'svc',
             table = 'svcmon',
             _class = 'env',
            ),
    'mon_overallstatus': HtmlTableColumn(
             title = 'Status',
             field='mon_overallstatus',
             display = False,
             img = 'svc',
             table = 'svcmon',
             _class='overallstatus',
            ),
    'mon_changed': HtmlTableColumn(
             title = 'Last status change',
             field='mon_changed',
             display = False,
             img = 'time16',
             table = 'svcmon',
            ),
    'mon_updated': HtmlTableColumn(
             title = 'Last status update',
             field='mon_updated',
             display = False,
             img = 'time16',
             table = 'svcmon',
             _class = 'datetime_daily',
            ),
    'mon_frozen': HtmlTableColumn(
             title = 'Frozen',
             field='mon_frozen',
             display = False,
             img = 'svc',
             table = 'svcmon',
            ),
    'mon_containerstatus': HtmlTableColumn(
             title = 'Container status',
             field='mon_containerstatus',
             display = False,
             img = 'svc',
             table = 'svcmon',
             _class="status",
            ),
    'mon_availstatus': HtmlTableColumn(
             title = 'Availability status',
             field='mon_availstatus',
             display = True,
             img = 'svc',
             table = 'svcmon',
             _class = 'availstatus',
            ),
    'mon_ipstatus': HtmlTableColumn(
             title = 'Ip status',
             field='mon_ipstatus',
             display = False,
             img = 'svc',
             table = 'svcmon',
             _class="status",
            ),
    'mon_fsstatus': HtmlTableColumn(
             title = 'Fs status',
             field='mon_fsstatus',
             display = False,
             img = 'svc',
             table = 'svcmon',
             _class="status",
            ),
    'mon_sharestatus': HtmlTableColumn(
             title = 'Share status',
             field='mon_sharestatus',
             display = False,
             img = 'svc',
             table = 'svcmon',
             _class="status",
            ),
    'mon_diskstatus': HtmlTableColumn(
             title = 'Disk status',
             field='mon_diskstatus',
             display = False,
             img = 'svc',
             table = 'svcmon',
             _class="status",
            ),
    'mon_syncstatus': HtmlTableColumn(
             title = 'Sync status',
             field='mon_syncstatus',
             display = False,
             img = 'svc',
             table = 'svcmon',
             _class="status",
            ),
    'mon_appstatus': HtmlTableColumn(
             title = 'App status',
             field='mon_appstatus',
             display = False,
             img = 'svc',
             table = 'svcmon',
             _class="status",
            ),
    'mon_hbstatus': HtmlTableColumn(
             title = 'Hb status',
             field='mon_hbstatus',
             display = False,
             img = 'svc',
             table = 'svcmon',
             _class="status",
            ),
    'mon_vmname': HtmlTableColumn(
             title = 'Container name',
             field='mon_vmname',
             display = True,
             img = 'svc',
             table = 'svcmon',
             _class = 'nodename_no_os',
            ),
    'mon_vmtype': HtmlTableColumn(
             title = 'Container type',
             field='mon_vmtype',
             display = True,
             img = 'svc',
             table = 'svcmon',
            ),
    'mon_vcpus': HtmlTableColumn(
             title = 'Vcpus',
             field='mon_vcpus',
             display = False,
             img = 'svc',
             table = 'svcmon',
            ),
    'mon_vmem': HtmlTableColumn(
             title = 'Vmem',
             field='mon_vmem',
             display = False,
             img = 'svc',
             table = 'svcmon',
            ),
    'mon_guestos': HtmlTableColumn(
             title = 'Guest OS',
             field='mon_guestos',
             display = False,
             img = 'svc',
             table = 'svcmon',
            ),
}


