#!/bin/ksh

PATH_SCRIPT="$(cd $(/usr/bin/dirname $(whence -- $0 || echo $0));pwd)"

# load config (for PASSWORD and DATADIR)
. $PATH_SCRIPT/$(basename $0).conf

DUMP_DIR=$PATH_SCRIPT/../dbdump
MYSQLDUMP="mysqldump -S $DATADIR/mysql.sock -u root -p$PASSWORD --hex-blob"
MYSQL="mysql -S $DATADIR/mysql.sock -u root -p$PASSWORD"

echo >$DUMP_DIR/schema.dump
cat - <<EOF >> $DUMP_DIR/schema.dump
create user if not exists opensvc@127.0.0.1 identified by 'opensvc';
create user if not exists pdns@127.0.0.1 identified by 'pdns';
create user if not exists readonly@127.0.0.1 identified by 'readonly';
EOF

# dump schema
$MYSQLDUMP --no-data --databases opensvc pdns | sed -e "s/SECURITY DEFINER/SECURITY INVOKER/" >> $DUMP_DIR/schema.dump

# compute readonly account readable tables grants
$MYSQL -B -N -e 'SELECT CONCAT("GRANT SELECT ON opensvc.", table_name, " TO readonly@127.0.0.1;") FROM information_schema.TABLES WHERE table_schema = "opensvc" AND table_name not in ("auth_node", "auth_user");' >>$DUMP_DIR/schema.dump

cat - <<EOF >> $DUMP_DIR/schema.dump
grant all privileges on opensvc.* to opensvc@127.0.0.1;
grant all privileges on pdns.* to pdns@127.0.0.1;
flush privileges;
EOF

sed -i 's/DEFINER=`opensvc`@`.*`/DEFINER=`root`@`127.0.0.1`/g' $DUMP_DIR/schema.dump

echo "use opensvc;" >$DUMP_DIR/data.dump
$MYSQLDUMP --where="repeats=0" opensvc scheduler_task >> $DUMP_DIR/data.dump
$MYSQLDUMP opensvc pkg_sig_provider >> $DUMP_DIR/data.dump
$MYSQLDUMP opensvc u_inc >> $DUMP_DIR/data.dump
$MYSQLDUMP opensvc digit >> $DUMP_DIR/data.dump
$MYSQLDUMP opensvc im_types >> $DUMP_DIR/data.dump
$MYSQLDUMP opensvc checks_defaults >> $DUMP_DIR/data.dump
$MYSQLDUMP opensvc billing >> $DUMP_DIR/data.dump
$MYSQLDUMP opensvc billing_agent >> $DUMP_DIR/data.dump
$MYSQLDUMP --where="privilege='T'" opensvc auth_group >> $DUMP_DIR/data.dump
$MYSQLDUMP --where="form_type='obj' or form_name='folder_compliance'" opensvc forms >> $DUMP_DIR/data.dump

cat - <<EOF >> $DUMP_DIR/data.dump
INSERT INTO sysrep_secure VALUES (1,'.*');
INSERT INTO auth_user (id, last_name, email, password) VALUES (1,'Manager','root@localhost.localdomain','sha512\$85f8c776fe663b25\$a9ab1f4ebd03fa7f2cf992bf7bc111e24a76397db7a228edc54a95e44e2cfbd50b7d83a5942a9c66da99c1f14c14b9ef070eef730460850c7eb48c1126236e96');
INSERT INTO auth_membership VALUES (1, 1, 2, 'F');
insert into auth_permission set group_id=(select id from auth_group where role = "Impersonate"), name="impersonate", table_name="auth_user", record_id=0;
insert ignore into forms_team_publication select NULL, id, (select id from auth_group where role="Everybody") from forms where form_type="obj";
EOF

